### ISSUE TITLE
find a less collision prone alternative to ctrl+shift+p (Windows)

### ISSUE THREAD

**Issue by meta-meta** [nasser/Socket#2]
ctrl+shift+p is mapped to command palette in Sublime for Windows. It's pretty disorienting to have it overridden after installing a package. I don't have a suggestion for a good replacement. Thoughts?

**Comment by selfsame** [comment]
this has been changed to `ctrl+shift+r` in the windows and linux bindings (f5783e125dfd518dd6b6b1dafb6bc62d3000e5c0)
